Facility:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      unique: true
      nullable: false
  oneToOne:
    Common:
      targetEntity: Common
      mappedBy: Facility
  manyToOne:
    User:
      targetEntity: User
      inversedBy: Facility
      joinColumns:
        user_id:
          referencedColumnName: id
