Mera\ManageBundle\Entity\Role:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        name:
            type: string
            unique: true
            nullable: false
    oneToOne:
        User:
            targetEntity: Mera\ManageBundle\Entity\User
            mappedBy: Role
