Mera\ManageBundle\Entity\User:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        first_name:
            type: string
            nullable: true
        last_name:
            type: string
            nullable: true
    oneToOne:
        Facility:
            targetEntity: Mera\ManageBundle\Entity\Facility
            mappedBy: User
            cascade:
                - all
