User:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  oneToOne:
    Role:
      targetEntity: Role
      inversedBy: User
      joinColumns:
        role_id:
          referencedColumnName: id
  oneToMany:
    Facility:
      targetEntity: Facility
      mappedBy: User
