Mera\ManageBundle\Entity\User:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
    oneToOne:
        Facility:
            targetEntity: Mera\ManageBundle\Entity\Facility
            mappedBy: User
            cascade:
                - all
