Mera\ManageBundle\Entity\User:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        username:
            type: string
            unique: true
            nullable: false
        password:
            type: string
            nullable: false
    oneToOne:
        Role:
            targetEntity: Mera\ManageBundle\Entity\Role
            inversedBy: User
            joinColumns:
                role_id:
                    referencedColumnName: id
    oneToMany:
        Facility:
            targetEntity: Mera\ManageBundle\Entity\Facility
            mappedBy: User
