#MeraUserBundle:
#    resource: "@MeraUserBundle/Controller/"
#    type:     annotation
#    prefix:   /

MeraAuditBundle:
    resource: "@MeraAuditBundle/Controller/"
    type:     annotation
    prefix:   /


MeraManageBundle:
    resource: "@MeraManageBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: MeraAuditBundle:Audit:audit}

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
