MeraAuditBundle:
    resource: "@MeraAuditBundle/Controller/"
    type:     annotation
    prefix:   /

MeraFacilityBundle:
    resource: "@MeraFacilityBundle/Controller/"
    type:     annotation
    prefix:   /

MeraManageBundle:
    resource: "@MeraManageBundle/Controller/"
    type:     annotation
    prefix:   /

MeraPostBundle:
  resource: "@MeraPostBundle/Controller/"
  type:     annotation
  prefix:   /
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal