Mera\AuditBundle\Entity\BuildingType:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    Buildings:
      targetEntity: Mera\AuditBundle\Entity\Building
      mappedBy: BuildingType
