Mera\AuditBundle\Entity\ChangeLog:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        first_name:
            type: string
            nullable: false
        last_name:
            type: string
            nullable: false
        action:
            type: string
            nullable: false
        action_data:
            type: string
            nullable: true
        created:
            type: datetime
            nullable: false
    manyToOne:
        Common:
            targetEntity: Mera\AuditBundle\Entity\Common
            inversedBy: ChangeLogs
            joinColumns:
                common_id:
                    referencedColumnName: id
                    nullable: false
