Mera\AuditBundle\Entity\Common:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        address_legal:
            type: string
            nullable: true
        address_actual:
            type: string
            nullable: true
        tin:
            type: string
            nullable: true
        cat:
            type: string
            nullable: true
        settlement_account:
            type: string
            nullable: true
        bic:
            type: string
            nullable: true
        bank_name:
            type: string
            nullable: true
        agrn:
            type: string
            nullable: true
        okved:
            type: string
            nullable: true
        okp:
            type: string
            nullable: true
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
    oneToOne:
        Facility:
            targetEntity: Mera\ManageBundle\Entity\Facility
            inversedBy: Common
            orphanRemoval: true
            cascade:
                - all
            joinColumns:
                facility_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
                    onUpdate: CASCADE
    oneToMany:
        Buildings:
            targetEntity: Mera\AuditBundle\Entity\Building
            mappedBy: Common
        ConstructElements:
            targetEntity: Mera\AuditBundle\Entity\ConstructElement
            mappedBy: Common
        ConsumptionMeters:
            targetEntity: Mera\AuditBundle\Entity\ConsumptionMeter
            mappedBy: Common
        ElectroEquipments:
            targetEntity: Mera\AuditBundle\Entity\ElectroEquipment
            mappedBy: Common
        LightsSystems:
            targetEntity: Mera\AuditBundle\Entity\LightsSystem
            mappedBy: Common
        Pipelines:
            targetEntity: Mera\AuditBundle\Entity\Pipeline
            mappedBy: Common
        FuelConsumptions:
            targetEntity: Mera\AuditBundle\Entity\FuelConsumption
            mappedBy: Common
        ExecutivePersons:
            targetEntity: Mera\AuditBundle\Entity\ExecutivePerson
            mappedBy: Common
        Personals:
            targetEntity: Mera\AuditBundle\Entity\Personal
            mappedBy: Common
        Files:
            targetEntity: Mera\AuditBundle\Entity\File
            mappedBy: Common
        Transformators:
            targetEntity: Mera\AuditBundle\Entity\Transformator
            mappedBy: Common
        FundsVolumes:
            targetEntity: Mera\AuditBundle\Entity\FundsVolume
            mappedBy: Common
        PersonalQuantitys:
            targetEntity: Mera\AuditBundle\Entity\PersonalQuantity
            mappedBy: Common
        ConsumedTariffs:
            targetEntity: Mera\AuditBundle\Entity\ConsumedTariff
            mappedBy: Common
        NaturalProductions:
            targetEntity: Mera\AuditBundle\Entity\NaturalProduction
            mappedBy: Common
        ConsumptionResources:
            targetEntity: Mera\AuditBundle\Entity\ConsumptionResource
            mappedBy: Common
