ConstructElement:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    area:
      type: decimal
      nullable: true
    description:
      type: text
      nullable: true
    width:
      type: decimal
      nullable: true
  manyToOne:
    ConstructElementType:
      targetEntity: ConstructElementType
      inversedBy: ConstructElements
      joinColumns:
        construct_element_type_id:
          referencedColumnName: id
    Common:
      targetEntity: Common
      inversedBy: ConstructElements
      cascade: [cascadeAll]
      joinColumns:
        common_id:
          referencedColumnName: id
          onDelete: CASCADE
          onUpdate: CASCADE
