Mera\AuditBundle\Entity\ConsumptionResource:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        year:
            type: integer
            nullable: true
        physical_quantity:
            type: decimal
            nullable: true
        financial_quantity:
            type: decimal
            nullable: true
    manyToOne:
        Common:
            targetEntity: Mera\AuditBundle\Entity\Common
            inversedBy: ConsumptionResources
            joinColumns:
                common_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
                    onUpdate: CASCADE
        ResourceType:
            targetEntity: Mera\AuditBundle\Entity\ResourceType
            inversedBy: ConsumptionResources
            joinColumns:
                resource_type_id:
                    referencedColumnName: id
                    nullable: false
