Mera\AuditBundle\Entity\ConsumedTariff:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        year:
            type: integer
            nullable: true
        tariff:
            type: string
            nullable: true
    manyToOne:
        ResourceType:
            targetEntity: Mera\AuditBundle\Entity\ResourceType
            joinColumns:
                resource_type_id:
                    referencedColumnName: id
                    nullable: false
        Common:
            targetEntity: Mera\AuditBundle\Entity\Common
            inversedBy: ConsumedTariffs
            cascade:
                - all
            joinColumns:
                Common_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
                    onUpdate: CASCADE
