Mera\AuditBundle\Entity\ConstructElement:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        area:
            type: decimal
            nullable: true
        description:
            type: text
            nullable: true
        width:
            type: decimal
            nullable: true
    manyToOne:
        ConstructElementType:
            targetEntity: Mera\AuditBundle\Entity\ConstructElementType
            inversedBy: ConstructElements
            joinColumns:
                construct_element_type_id:
                    referencedColumnName: id
                    nullable: false
        Common:
            targetEntity: Mera\AuditBundle\Entity\Common
            inversedBy: ConstructElements
            orphanRemoval: true
            cascade:
                - all
            joinColumns:
                common_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
                    onUpdate: CASCADE
