Mera\AuditBundle\Entity\ConsumptionMeterType:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    ConsumptionMeters:
      targetEntity: Mera\AuditBundle\Entity\ConsumptionMeter
      mappedBy: ConsumptionMeterType
