Mera\AuditBundle\Entity\ElectroEquipment:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    quantity:
      type: integer
      nullable: true
    power:
      type: decimal
      nullable: true
    work_duration:
      type: decimal
      nullable: true
  manyToOne:
    Common:
      targetEntity: Mera\AuditBundle\Entity\Common
      inversedBy: ElectroEquipments
      joinColumns:
        common_id:
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
          onUpdate: CASCADE
    ElectroEquipmentType:
      targetEntity: Mera\AuditBundle\Entity\ElectroEquipmentType
      inversedBy: ElectroEquipments
      joinColumns:
        electro_equipment_type_id:
          referencedColumnName: id
          nullable: false
