Mera\AuditBundle\Entity\EnergySavingMeasure:
    type: entity
    fields: null
    manyToOne:
        Common:
            targetEntity: Mera\AuditBundle\Entity\Common
            inversedBy: EnergySavingMeasures
            joinColumns:
                common_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
                    onUpdate: CASCADE
