Mera\AuditBundle\Entity\File:
    type: entity
    inheritanceType: SINGLE_TABLE
    fields:
        id:
            id: true
            generator:
                strategy: AUTO
        name:
            nullable: false
    manyToOne:
        Common:
            targetEntity: Mera\AuditBundle\Entity\Common
            inversedBy: Files
            cascade:
                - all
            joinColumns:
                common_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
                    onUpdate: CASCADE
    discriminatorColumn:
        name: for
        length: 255
        type: text
    discriminatorMap:
        FloorPlan: Mera\AuditBundle\Entity\FloorPlan
        HeatingSystem: Mera\AuditBundle\Entity\HeatingSystem
        VentilationSystem: Mera\AuditBundle\Entity\VentilationSystem
        EnergySavingProgram: Mera\AuditBundle\Entity\EnergySavingProgram
        EnergySavingMeasure: Mera\AuditBundle\Entity\EnergySavingMeasure
        PowerCircuit: Mera\AuditBundle\Entity\PowerCircuit
        SupplyContract: Mera\AuditBundle\Entity\SupplyContract
