Mera\AuditBundle\Entity\FuelConsumption:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        type:
            type: string
            nullable: true
        quantity:
            type: integer
            nullable: true
        load_capacity:
            type: decimal
            nullable: true
        passengers:
            type: integer
            nullable: true
        consumption:
            type: decimal
            nullable: true
        work_duration:
            type: decimal
            nullable: true
        total_consumed:
            type: decimal
            nullable: true
    manyToOne:
        Common:
            targetEntity: Mera\AuditBundle\Entity\Common
            inversedBy: FuelConsumptions
            joinColumns:
                common_id:
                    referencedColumnName: id
        FuelType:
            targetEntity: Mera\AuditBundle\Entity\FuelType
            inversedBy: FuelConsumptions
            joinColumns:
                fuel_type_id:
                    referencedColumnName: id
