FuelType:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    FuelConsumptions:
      targetEntity: FuelConsumption
      mappedBy: FuelType
