Mera\AuditBundle\Entity\FuelType:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        name:
            type: string
            nullable: false
    oneToMany:
        FuelConsumptions:
            targetEntity: Mera\AuditBundle\Entity\FuelConsumption
            mappedBy: FuelType
