LightsSystemPlace:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    LightsSystems:
      targetEntity: LightsSystem
      mappedBy: LightsSystemPlace
