Mera\AuditBundle\Entity\PersonalQuantity:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        year:
            type: integer
            nullable: true
        quantity:
            type: integer
            nullable: true
    manyToOne:
        Common:
            targetEntity: Mera\AuditBundle\Entity\Common
            inversedBy: PersonalQuantitys
            orphanRemoval: true
            cascade:
                - all
            joinColumns:
                Common_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
                    onUpdate: CASCADE
