PipelineInstallationType:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    Pipelines:
      targetEntity: Pipeline
      mappedBy: PipelineInstallationType
