Mera\AuditBundle\Entity\ResourceType:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        name:
            type: string
            nullable: false
    oneToMany:
        ConsumptionResources:
            targetEntity: Mera\AuditBundle\Entity\ConsumptionResource
            mappedBy: ResourceType
