Mera\PostBundle\Entity\Building:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        name:
            type: string
            nullable: true
        year:
            type: integer
            nullable: true
        floors:
            type: integer
            nullable: true
        height_ceilings:
            type: integer
            nullable: true
        height_building:
            type: integer
            nullable: true
        volume_building:
            type: integer
            nullable: true
        volume_heated:
            type: integer
            nullable: true
        area_total:
            type: integer
            nullable: true
        area_glazing:
            type: integer
            nullable: true
        perimeter_building:
            type: integer
            nullable: true
        depreciation_actual:
            type: integer
            nullable: true
        depreciation_physical:
            type: integer
            nullable: true
    manyToOne:
        PostOffice:
            targetEntity: Mera\PostBundle\Entity\PostOffice
            inversedBy: Buildings
            joinColumns:
                post_office_id:
                    referencedColumnName: id
