Mera\PostBundle\Entity\PostOffice:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        name:
            type: string
            unique: true
            nullable: false
        email:
            type: string
            nullable: false
