Mera\PostBundle\Entity\PostOffice:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        name:
            type: string
            unique: true
            nullable: false
        email:
            type: string
            nullable: false
    oneToOne:
        Common:
            targetEntity: Mera\PostBundle\Entity\Common
            mappedBy: PostOffice
    oneToMany:
        Buildings:
            targetEntity: Mera\PostBundle\Entity\Building
            mappedBy: PostOffice
